#!/usr/bin/env bash
set -e

fail() {
  >&2 echo "$@"
  exit 1
}

test -z "$(git status --porcelain)" || fail "Commit changes before releasing"

bump="$1"

echo "Bumping $bump version..."
bundle exec rake "version:bump:$bump"
version="$(cat VERSION)"

echo "Updating gemspec..."
bundle exec rake gemspec

tag="v${version}"
echo "Committing..."
git commit -am "$tag"

echo "Creating tag $tag..."
git tag "$tag"

echo "Pushing..."
git push --tags origin main
