name: build

on:
  push:
    paths-ignore:
      - ".ackrc"
      - ".editorconfig"
      - ".gitignore"
      - ".screenrc"
      - "scripts/**"
      - "TODO.md"
      - ".tool-versions"
    tags-ignore:
      - "**"
  schedule:
    # Minute (0-59), Hour (0-23), Day of the month (1-31), Month of the Year (1-12), Day of the week (0-6, 0 = Sunday)
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  automated-tests:
    runs-on: ubuntu-20.04
    name: Run automated tests
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Run automated tests & generate code coverage report
        run: |
          bundle exec rake
