name: build

on:
  push:
    branches:
      - '*'
  schedule:
    # Minute (0-59), Hour (0-23), Day of the month (1-31), Month of the Year (1-12), Day of the week (0-6, 0 = Sunday)
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  automated-tests:
    runs-on: ubuntu-24.04
    name: Run automated tests
    strategy:
      matrix:
        ruby-version: [3.1.6, 3.2.5, 3.3.5]
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Run automated tests
        run: |
          bundle exec rake

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
