name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-latest:
    name: Test & release the gem
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Run automated tests
        env:
          COVERAGE_DISABLED: true
        run: |
          bundle exec rake

      - name: Build the gem
        run: |
          gem build -o pkg/release.gem gitenv.gemspec

      - name: Create ~/.gem/credentials
        env:
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
        run: |
          mkdir -p $HOME/.gem
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials

      - name: Release the gem
        run: |
          gem push pkg/release.gem
